---
- name: Update RHEL server and install httpd and open port 8080
  hosts: web
  become: true
  tasks:
    - name: Install httpd servers
      ansible.builtin.package:
        name: httpd
        state: latest
    - name: Open port 8080
      ansible.posix.firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: true
